"""analyse_encoding.py

Analyze and visualize encoded tactile datasets generated by scripts/event_transform.py.

This script scans data_path for encoded pickle files, infers their encoding schema,
and writes per-sample plots into figures/encoding_analysis/<file_stem>/.
"""

from __future__ import annotations

import argparse
import pickle as pkl
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
from tqdm import tqdm


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Analyze all encoded data files generated by event_transform.py"
    )
    parser.add_argument(
        "--data-path",
        type=Path,
        default=Path("data/100Hz"),
        help="Directory containing encoded pickle files",
    )
    parser.add_argument(
        "--output-root",
        type=Path,
        default=Path("figures/encoding_analysis"),
        help="Root directory for generated figures",
    )
    parser.add_argument(
        "--pattern",
        type=str,
        default="*_encoded.pkl",
        help="Glob pattern for encoded files",
    )
    parser.add_argument(
        "--samples-per-letter",
        type=int,
        default=5,
        help="Maximum number of trials to visualize per letter",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random seed for trial sampling",
    )
    return parser.parse_args()


def infer_schema(out_dict: dict) -> str:
    keys = set(out_dict.keys())
    if {"fa_spikes", "sa_spikes"}.issubset(keys):
        return "mechanoreceptor"
    if {"ON_spikes", "OFF_spikes"}.issubset(keys):
        return "sigma_delta"
    if "spikes" in keys:
        return "neuron_model"
    return "unknown"


def select_indices_by_letter(
    letters_list: list,
    samples_per_letter: int,
    rng: np.random.Generator,
) -> list[int]:
    unique_letters = sorted(set(letters_list))
    selected_indices: list[int] = []

    for letter in unique_letters:
        indices = [i for i, label in enumerate(letters_list) if label == letter]
        n_samples = min(samples_per_letter, len(indices))
        if n_samples == 0:
            continue
        picked = rng.choice(indices, size=n_samples, replace=False)
        selected_indices.extend(picked.tolist())

    return selected_indices


def plot_mechanoreceptor(
    letter,
    idx: int,
    taxel_data: np.ndarray,
    timestamps: np.ndarray,
    fa_spikes: np.ndarray,
    sa_spikes: np.ndarray,
    output_dir: Path,
) -> None:
    fig, (ax_sensor, ax_fa, ax_sa) = plt.subplots(
        3,
        1,
        figsize=(12, 8),
        gridspec_kw={"height_ratios": [2, 1, 1]},
    )

    ax_sensor.plot(timestamps, taxel_data)
    ax_sensor.set_title(f"Taxel Data for Letter '{letter}'")
    ax_sensor.set_xlabel("Time (s)")
    ax_sensor.set_ylabel("Taxel Value")
    ax_sensor.set_xlim(timestamps[0], timestamps[-1])

    if fa_spikes.shape[0] > 0:
        ax_fa.scatter(fa_spikes[:, 0], fa_spikes[:, 1], s=1)
    ax_fa.set_title(f"FA-I Spikes for Letter '{letter}'")
    ax_fa.set_xlabel("Time (s)")
    ax_fa.set_ylabel("Channel")
    ax_fa.set_xlim(timestamps[0], timestamps[-1])
    ax_fa.set_ylim(-1, 13)

    if sa_spikes.shape[0] > 0:
        ax_sa.scatter(sa_spikes[:, 0], sa_spikes[:, 1], s=1, color="orange")
    ax_sa.set_title(f"SA-II Spikes for Letter '{letter}'")
    ax_sa.set_xlabel("Time (s)")
    ax_sa.set_ylabel("Channel")
    ax_sa.set_xlim(timestamps[0], timestamps[-1])
    ax_sa.set_ylim(-1, 13)

    fig.tight_layout()
    fig.savefig(output_dir / f"letter_{letter}_idx_{idx}.pdf")
    plt.close(fig)


def plot_sigma_delta(
    letter,
    idx: int,
    taxel_data: np.ndarray,
    timestamps: np.ndarray,
    on_spikes: np.ndarray,
    off_spikes: np.ndarray,
    output_dir: Path,
) -> None:
    fig, (ax_sensor, ax_on, ax_off) = plt.subplots(
        3,
        1,
        figsize=(12, 8),
        gridspec_kw={"height_ratios": [2, 1, 1]},
    )

    ax_sensor.plot(timestamps, taxel_data)
    ax_sensor.set_title(f"Taxel Data for Letter '{letter}'")
    ax_sensor.set_xlabel("Time (s)")
    ax_sensor.set_ylabel("Taxel Value")
    ax_sensor.set_xlim(timestamps[0], timestamps[-1])

    if on_spikes.shape[0] > 0:
        ax_on.scatter(on_spikes[:, 0], on_spikes[:, 1], s=1, color="green")
    ax_on.set_title(f"ON Spikes for Letter '{letter}'")
    ax_on.set_xlabel("Time (s)")
    ax_on.set_ylabel("Channel")
    ax_on.set_xlim(timestamps[0], timestamps[-1])
    ax_on.set_ylim(-1, 13)

    if off_spikes.shape[0] > 0:
        ax_off.scatter(off_spikes[:, 0], off_spikes[:, 1], s=1, color="red")
    ax_off.set_title(f"OFF Spikes for Letter '{letter}'")
    ax_off.set_xlabel("Time (s)")
    ax_off.set_ylabel("Channel")
    ax_off.set_xlim(timestamps[0], timestamps[-1])
    ax_off.set_ylim(-1, 13)

    fig.tight_layout()
    fig.savefig(output_dir / f"letter_{letter}_idx_{idx}.pdf")
    plt.close(fig)


def plot_neuron_model(
    letter,
    idx: int,
    taxel_data: np.ndarray,
    timestamps: np.ndarray,
    spikes: np.ndarray,
    output_dir: Path,
) -> None:
    fig, (ax_sensor, ax_spk) = plt.subplots(
        2,
        1,
        figsize=(12, 7),
        gridspec_kw={"height_ratios": [2, 1]},
    )

    ax_sensor.plot(timestamps, taxel_data)
    ax_sensor.set_title(f"Taxel Data for Letter '{letter}'")
    ax_sensor.set_xlabel("Time (s)")
    ax_sensor.set_ylabel("Taxel Value")
    ax_sensor.set_xlim(timestamps[0], timestamps[-1])

    if spikes.shape[0] > 0:
        ax_spk.scatter(spikes[:, 0], spikes[:, 1], s=1, color="purple")
    ax_spk.set_title(f"Neuron-Model Spikes for Letter '{letter}'")
    ax_spk.set_xlabel("Time (s)")
    ax_spk.set_ylabel("Channel")
    ax_spk.set_xlim(timestamps[0], timestamps[-1])
    ax_spk.set_ylim(-1, 13)

    fig.tight_layout()
    fig.savefig(output_dir / f"letter_{letter}_idx_{idx}.pdf")
    plt.close(fig)


def analyze_one_file(
    encoded_file: Path,
    output_root: Path,
    samples_per_letter: int,
    rng: np.random.Generator,
) -> None:
    with encoded_file.open("rb") as f:
        out_dict = pkl.load(f)

    schema = infer_schema(out_dict)
    if schema == "unknown":
        print(f"Skipping {encoded_file.name}: unsupported schema keys {list(out_dict.keys())}")
        return

    letters_list = out_dict["letter"]
    taxel_data_list = out_dict["taxel_data"]
    timestamps_list = out_dict["timestamps"]

    output_dir = output_root / encoded_file.stem
    output_dir.mkdir(parents=True, exist_ok=True)

    selected_indices = select_indices_by_letter(letters_list, samples_per_letter, rng)
    print(
        f"Analyzing {encoded_file.name} ({schema}) with "
        f"{len(selected_indices)} selected trials."
    )

    for idx in tqdm(selected_indices, desc=f"Plotting {encoded_file.stem}", leave=False):
        letter = letters_list[idx]
        taxel_data = taxel_data_list[idx]
        timestamps = timestamps_list[idx]

        if schema == "mechanoreceptor":
            plot_mechanoreceptor(
                letter,
                idx,
                taxel_data,
                timestamps,
                out_dict["fa_spikes"][idx],
                out_dict["sa_spikes"][idx],
                output_dir,
            )
        elif schema == "sigma_delta":
            plot_sigma_delta(
                letter,
                idx,
                taxel_data,
                timestamps,
                out_dict["ON_spikes"][idx],
                out_dict["OFF_spikes"][idx],
                output_dir,
            )
        else:
            plot_neuron_model(
                letter,
                idx,
                taxel_data,
                timestamps,
                out_dict["spikes"][idx],
                output_dir,
            )


if __name__ == "__main__":
    args = parse_args()
    args.output_root.mkdir(parents=True, exist_ok=True)

    encoded_files = sorted(args.data_path.glob(args.pattern))
    if not encoded_files:
        print(f"No encoded files found in {args.data_path} with pattern '{args.pattern}'.")
        raise SystemExit(0)

    rng = np.random.default_rng(args.seed)

    for encoded_file in encoded_files:
        analyze_one_file(
            encoded_file=encoded_file,
            output_root=args.output_root,
            samples_per_letter=args.samples_per_letter,
            rng=rng,
        )

    print(f"Done. Figures saved under: {args.output_root}")
