"""analyse_encoding.py

Analyze and visualize encoded tactile datasets generated by scripts/event_transform.py.

This script scans data_path for encoded pickle files, infers their encoding schema,
and writes per-sample plots into figures/encoding_analysis/<file_stem>/.
"""

from __future__ import annotations

import argparse
import pickle as pkl
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
from tqdm import tqdm


ENCODING_CHOICES = ["all", "mechanoreceptor", "sigma_delta", "neuron_model"]
NEURON_MODEL_CHOICES = [
    "AdExLIF_neuron",
    "CuBaLIF_neuron",
    "IZ_neuron",
    "LIF_neuron",
    "MN_neuron",
]


def prompt_text(prompt: str, default: str | None = None) -> str:
    """Prompt for free text, accepting Enter as the default when provided."""
    if default is None:
        return input(f"{prompt}: ").strip()

    value = input(f"{prompt} [{default}]: ").strip()
    return value or default


def prompt_choice(prompt: str, choices: list[str], default: str) -> str:
    """Prompt for a value from a fixed list."""
    while True:
        print(f"\n{prompt}")
        for index, choice in enumerate(choices, start=1):
            marker = " (default)" if choice == default else ""
            print(f"  {index}. {choice}{marker}")

        raw_value = input(f"Select 1-{len(choices)} or type a value [{default}]: ").strip()
        if not raw_value:
            return default
        if raw_value.isdigit():
            selected_index = int(raw_value)
            if 1 <= selected_index <= len(choices):
                return choices[selected_index - 1]
        if raw_value in choices:
            return raw_value
        print(f"Please choose one of: {', '.join(choices)}")


def prompt_int(prompt: str, default: int) -> int:
    """Prompt until a valid int is entered."""
    while True:
        raw_value = prompt_text(prompt, str(default))
        try:
            return int(raw_value)
        except ValueError:
            print("Please enter an integer.")


def default_output_name(encoding_type: str, neuron_model: str | None = None) -> str:
    """Build the default output folder name used under --output-root."""
    if encoding_type == "neuron_model":
        model = neuron_model or "neuron_model"
        return f"{encoding_type}_{model}"
    if encoding_type == "all":
        return "all_encoded_data"
    return encoding_type


def prompt_interactive_args(args: argparse.Namespace) -> argparse.Namespace:
    """Collect analysis options in a guided interactive flow."""
    print("Interactive encoded-data analysis")
    print("Use Ctrl+C to cancel.\n")

    args.encoding_type = prompt_choice("Encoding to analyze", ENCODING_CHOICES, args.encoding_type)

    if args.encoding_type == "neuron_model":
        args.neuron_model = prompt_choice("Neuron model", NEURON_MODEL_CHOICES, args.neuron_model)
    else:
        args.neuron_model = None

    args.samples_per_letter = prompt_int("Samples per letter", args.samples_per_letter)
    args.data_path = Path(prompt_text("Data path", str(args.data_path)))
    args.output_root = Path(prompt_text("Output root", str(args.output_root)))

    default_name = default_output_name(args.encoding_type, args.neuron_model)
    output_name = prompt_text(
        "Output name (used as output folder under output root)",
        default_name,
    )
    args.output_name = output_name.strip() or default_name
    return args


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Analyze all encoded data files generated by event_transform.py"
    )
    parser.add_argument(
        "--interactive",
        action="store_true",
        help="Ask for analysis options in a guided terminal wizard.",
    )
    parser.add_argument(
        "--data-path",
        type=Path,
        default=Path("data/100Hz"),
        help="Directory containing encoded pickle files",
    )
    parser.add_argument(
        "--output-root",
        type=Path,
        default=Path("figures/encoding_analysis"),
        help="Root directory for generated figures",
    )
    parser.add_argument(
        "--pattern",
        type=str,
        default="*_encoded*.pkl",
        help="Glob pattern for encoded files",
    )
    parser.add_argument(
        "--encoding-type",
        choices=ENCODING_CHOICES,
        default="all",
        help="Analyze all encoded files or a single encoding pipeline.",
    )
    parser.add_argument(
        "--neuron-model",
        choices=NEURON_MODEL_CHOICES,
        default="MN_neuron",
        help="Neuron model to analyze when --encoding-type neuron_model.",
    )
    parser.add_argument(
        "--output-name",
        type=str,
        default=None,
        help=(
            "Optional output folder name under --output-root. "
            "Defaults to encoding name, or encoding+model for neuron_model."
        ),
    )
    parser.add_argument(
        "--samples-per-letter",
        type=int,
        default=5,
        help="Maximum number of trials to visualize per letter",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random seed for trial sampling",
    )
    args = parser.parse_args()
    if args.interactive:
        try:
            return prompt_interactive_args(args)
        except KeyboardInterrupt:
            print("\nCancelled.")
            raise SystemExit(1) from None

    if args.encoding_type != "neuron_model":
        args.neuron_model = None

    if not args.output_name:
        args.output_name = default_output_name(args.encoding_type, args.neuron_model)

    return args


def stem_matches_encoded_family(path: Path, family_stem: str) -> bool:
    """Return True for the base encoded file and subset-suffixed variants."""
    return path.stem == family_stem or path.stem.startswith(f"{family_stem}_")


def filter_encoded_files(
    encoded_files: list[Path],
    encoding_type: str,
    neuron_model: str | None,
) -> list[Path]:
    """Filter files by encoding family and optional neuron model."""
    if encoding_type == "all":
        return encoded_files

    if encoding_type == "mechanoreceptor":
        return [
            f for f in encoded_files
            if stem_matches_encoded_family(f, "mechanoreceptor_encoded")
        ]

    if encoding_type == "sigma_delta":
        return [
            f for f in encoded_files
            if stem_matches_encoded_family(f, "sigma_delta_encoded")
        ]

    known_non_neuron = {"mechanoreceptor_encoded", "sigma_delta_encoded"}
    neuron_files = [
        f for f in encoded_files
        if not any(stem_matches_encoded_family(f, stem) for stem in known_non_neuron)
    ]

    if neuron_model:
        target_stem = f"{neuron_model}_encoded"
        neuron_files = [
            f for f in neuron_files
            if stem_matches_encoded_family(f, target_stem)
        ]

    return neuron_files


def infer_schema(out_dict: dict) -> str:
    keys = set(out_dict.keys())
    if {"fa_spikes", "sa_spikes"}.issubset(keys):
        return "mechanoreceptor"
    if {"ON_spikes", "OFF_spikes"}.issubset(keys):
        return "sigma_delta"
    if "spikes" in keys:
        return "neuron_model"
    return "unknown"


def select_indices_by_letter(
    letters_list: list,
    samples_per_letter: int,
    rng: np.random.Generator,
) -> list[int]:
    unique_letters = sorted(set(letters_list))
    selected_indices: list[int] = []

    for letter in unique_letters:
        indices = [i for i, label in enumerate(letters_list) if label == letter]
        n_samples = min(samples_per_letter, len(indices))
        if n_samples == 0:
            continue
        picked = rng.choice(indices, size=n_samples, replace=False)
        selected_indices.extend(picked.tolist())

    return selected_indices


def plot_mechanoreceptor(
    letter,
    idx: int,
    taxel_data: np.ndarray,
    timestamps: np.ndarray,
    fa_spikes: np.ndarray,
    sa_spikes: np.ndarray,
    output_dir: Path,
) -> None:
    fig, (ax_sensor, ax_fa, ax_sa) = plt.subplots(
        3,
        1,
        figsize=(12, 8),
        gridspec_kw={"height_ratios": [2, 1, 1]},
    )

    ax_sensor.plot(timestamps, taxel_data)
    ax_sensor.set_title(f"Taxel Data for Letter '{letter}'")
    ax_sensor.set_xlabel("Time (s)")
    ax_sensor.set_ylabel("Taxel Value")
    ax_sensor.set_xlim(timestamps[0], timestamps[-1])

    if fa_spikes.shape[0] > 0:
        ax_fa.scatter(fa_spikes[:, 0], fa_spikes[:, 1], s=1)
    ax_fa.set_title(f"FA-I Spikes for Letter '{letter}'")
    ax_fa.set_xlabel("Time (s)")
    ax_fa.set_ylabel("Channel")
    ax_fa.set_xlim(timestamps[0], timestamps[-1])
    ax_fa.set_ylim(-1, 13)

    if sa_spikes.shape[0] > 0:
        ax_sa.scatter(sa_spikes[:, 0], sa_spikes[:, 1], s=1, color="orange")
    ax_sa.set_title(f"SA-II Spikes for Letter '{letter}'")
    ax_sa.set_xlabel("Time (s)")
    ax_sa.set_ylabel("Channel")
    ax_sa.set_xlim(timestamps[0], timestamps[-1])
    ax_sa.set_ylim(-1, 13)

    fig.tight_layout()
    fig.savefig(output_dir / f"letter_{letter}_idx_{idx}.pdf")
    plt.close(fig)


def plot_sigma_delta(
    letter,
    idx: int,
    taxel_data: np.ndarray,
    timestamps: np.ndarray,
    on_spikes: np.ndarray,
    off_spikes: np.ndarray,
    output_dir: Path,
) -> None:
    fig, (ax_sensor, ax_on, ax_off) = plt.subplots(
        3,
        1,
        figsize=(12, 8),
        gridspec_kw={"height_ratios": [2, 1, 1]},
    )

    ax_sensor.plot(timestamps, taxel_data)
    ax_sensor.set_title(f"Taxel Data for Letter '{letter}'")
    ax_sensor.set_xlabel("Time (s)")
    ax_sensor.set_ylabel("Taxel Value")
    ax_sensor.set_xlim(timestamps[0], timestamps[-1])

    if on_spikes.shape[0] > 0:
        ax_on.scatter(on_spikes[:, 0], on_spikes[:, 1], s=1, color="green")
    ax_on.set_title(f"ON Spikes for Letter '{letter}'")
    ax_on.set_xlabel("Time (s)")
    ax_on.set_ylabel("Channel")
    ax_on.set_xlim(timestamps[0], timestamps[-1])
    ax_on.set_ylim(-1, 13)

    if off_spikes.shape[0] > 0:
        ax_off.scatter(off_spikes[:, 0], off_spikes[:, 1], s=1, color="red")
    ax_off.set_title(f"OFF Spikes for Letter '{letter}'")
    ax_off.set_xlabel("Time (s)")
    ax_off.set_ylabel("Channel")
    ax_off.set_xlim(timestamps[0], timestamps[-1])
    ax_off.set_ylim(-1, 13)

    fig.tight_layout()
    fig.savefig(output_dir / f"letter_{letter}_idx_{idx}.pdf")
    plt.close(fig)


def plot_neuron_model(
    letter,
    idx: int,
    taxel_data: np.ndarray,
    timestamps: np.ndarray,
    spikes: np.ndarray,
    output_dir: Path,
) -> None:
    fig, (ax_sensor, ax_spk) = plt.subplots(
        2,
        1,
        figsize=(12, 7),
        gridspec_kw={"height_ratios": [2, 1]},
    )

    ax_sensor.plot(timestamps, taxel_data)
    ax_sensor.set_title(f"Taxel Data for Letter '{letter}'")
    ax_sensor.set_xlabel("Time (s)")
    ax_sensor.set_ylabel("Taxel Value")
    ax_sensor.set_xlim(timestamps[0], timestamps[-1])

    if spikes.shape[0] > 0:
        ax_spk.scatter(spikes[:, 0], spikes[:, 1], s=1, color="purple")
    ax_spk.set_title(f"Neuron-Model Spikes for Letter '{letter}'")
    ax_spk.set_xlabel("Time (s)")
    ax_spk.set_ylabel("Channel")
    ax_spk.set_xlim(timestamps[0], timestamps[-1])
    ax_spk.set_ylim(-1, 13)

    fig.tight_layout()
    fig.savefig(output_dir / f"letter_{letter}_idx_{idx}.pdf")
    plt.close(fig)


def analyze_one_file(
    encoded_file: Path,
    output_root: Path,
    samples_per_letter: int,
    rng: np.random.Generator,
    output_subdir: str | None = None,
) -> None:
    with encoded_file.open("rb") as f:
        out_dict = pkl.load(f)

    if not isinstance(out_dict, dict):
        print(
            f"Skipping {encoded_file.name}: expected a dictionary, "
            f"got {type(out_dict).__name__}."
        )
        return

    schema = infer_schema(out_dict)
    if schema == "unknown":
        print(f"Skipping {encoded_file.name}: unsupported schema keys {list(out_dict.keys())}")
        return

    missing_keys = [
        key for key in ["letter", "taxel_data", "timestamps"]
        if key not in out_dict
    ]
    if missing_keys:
        print(f"Skipping {encoded_file.name}: missing keys {missing_keys}")
        return

    letters_list = out_dict["letter"]
    taxel_data_list = out_dict["taxel_data"]
    timestamps_list = out_dict["timestamps"]

    output_dir = output_root / (output_subdir or encoded_file.stem)
    output_dir.mkdir(parents=True, exist_ok=True)

    selected_indices = select_indices_by_letter(letters_list, samples_per_letter, rng)
    print(
        f"Analyzing {encoded_file.name} ({schema}) with "
        f"{len(selected_indices)} selected trials."
    )

    for idx in tqdm(selected_indices, desc=f"Plotting {encoded_file.stem}", leave=False):
        letter = letters_list[idx]
        taxel_data = taxel_data_list[idx]
        timestamps = timestamps_list[idx]

        if schema == "mechanoreceptor":
            plot_mechanoreceptor(
                letter,
                idx,
                taxel_data,
                timestamps,
                out_dict["fa_spikes"][idx],
                out_dict["sa_spikes"][idx],
                output_dir,
            )
        elif schema == "sigma_delta":
            plot_sigma_delta(
                letter,
                idx,
                taxel_data,
                timestamps,
                out_dict["ON_spikes"][idx],
                out_dict["OFF_spikes"][idx],
                output_dir,
            )
        else:
            plot_neuron_model(
                letter,
                idx,
                taxel_data,
                timestamps,
                out_dict["spikes"][idx],
                output_dir,
            )


if __name__ == "__main__":
    args = parse_args()
    args.output_root.mkdir(parents=True, exist_ok=True)

    encoded_files = sorted(args.data_path.glob(args.pattern))
    encoded_files = filter_encoded_files(
        encoded_files=encoded_files,
        encoding_type=args.encoding_type,
        neuron_model=args.neuron_model,
    )

    if not encoded_files:
        model_hint = f" and neuron model '{args.neuron_model}'" if args.neuron_model else ""
        print(
            "No encoded files found in "
            f"{args.data_path} with pattern '{args.pattern}' "
            f"for encoding '{args.encoding_type}'{model_hint}."
        )
        raise SystemExit(0)

    rng = np.random.default_rng(args.seed)

    for encoded_file in encoded_files:
        # Use one custom folder only when there is a single target; otherwise keep
        # one folder per file so subset-suffixed outputs do not overwrite each other.
        output_subdir = (
            args.output_name
            if args.encoding_type != "all" and len(encoded_files) == 1
            else None
        )
        analyze_one_file(
            encoded_file=encoded_file,
            output_root=args.output_root,
            samples_per_letter=args.samples_per_letter,
            rng=rng,
            output_subdir=output_subdir,
        )

    print(f"Done. Figures saved under: {args.output_root}")
